src/objects/Campaign__c.object
<CustomObject>
    <description>Campaign records for all Marketing Plans.</description>
    <fields>
        <fullName>Brand_Quality__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand Quality</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Tags__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Brand Quality</value>
            </filterItems>
            <filterItems>
                <field>Tags__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tags__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IOCode__c</fullName>
        <label>IO Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentMarketingPlan__c</fullName>
        <label>Master Marketing Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - FIELD</value>
            </filterItems>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - NATL MKTG</value>
            </filterItems>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - NATL ACCTS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MarketingPlan__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <description>Field used to view the current status of the IO generation.</description>
        <inlineHelpText>Field used to view the current status of the IO generation.</inlineHelpText>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>IO Not Requested</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>IO Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Company_Code__c</fullName>
        <formula>ParentMarketingPlan__r.SAP_Company_Code__c</formula>
        <label>SAP Company Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Controlling_Area__c</fullName>
        <formula>ParentMarketingPlan__r.SAP_Controlling_Area__c</formula>
        <label>SAP Controlling Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Cost_Center__c</fullName>
        <formula>ParentMarketingPlan__r.SAP_Cost_Center__c</formula>
        <label>SAP Cost Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>ParentMarketingPlan__r.Territory__r.Name</formula>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>text (ParentMarketingPlan__r.Year__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MarketingPlan__c.object
<CustomObject>
    <description>Marketing Plan Budget records for all levels of the hierarchy.</description>
    <fields>
        <fullName>Next_IO_Sequence__c</fullName>
        <description>Stores the next available IO ending sequence for all the campaigns under this Marketing Plan. Used by system to auto-generate IO Codes on Campaigns.</description>
        <label>Next IO Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentMarketingPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Marketing Plan</label>
        <referenceTo>MarketingPlan__c</referenceTo>
        <relationshipLabel>Related Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Company_Code__c</fullName>
        <label>SAP Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Controlling_Area__c</fullName>
        <label>SAP Controlling Area</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Cost_Center__c</fullName>
        <label>SAP Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Tags__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Territory</value>
            </filterItems>
            <filterItems>
                <field>Tags__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tags__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2015</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tags__c.object
<CustomObject>
    <description>Brand, Brand Quality, and Territory hierarchy data table.</description>
    <fields>
        <fullName>IOCodeSegment__c</fullName>
        <label>IO Code Segment</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Brand Record Type.</description>
        <label>Brand</label>
    </recordTypes>
    <recordTypes>
        <fullName>Territory</fullName>
        <active>true</active>
        <description>Territory Record Type.</description>
        <label>Territory</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BI_CampaignIntegrationLogic.cls
public without sharing class BI_CampaignIntegrationLogic {
	
	public static List<CampaignIOResult> generateIOCodes(set<Id> campaignIds) {        
        System.debug(LoggingLevel.INFO,'Entered BI_CampaignIntegrationLogic.generateIOCodes');
        System.debug(LoggingLevel.INFO,'# Campaigns passed in: ' + campaignIds.size());
  		
  		//Retrieve all the Campaigns grouped by parent Marketing Plan. Assure all other info
  		//needed to generate IO codes is retrieved.
  		Map<Id, BI_IOSequenceGroup> groups = GetIOGroupings(campaignIds);
  		List<CampaignIOResult> results = new List<CampaignIOResult>();
  		List<Campaign__c> updateCampaigns = new List<Campaign__c>();     
  		List<MarketingPlan__c> updatePlans = new List<MarketingPlan__c>();             
  		                                 		 		
  		//Foreach grouping, generate the IO codes, update the Campaigns, and update the parent Marketing Plan with next sequence number.
  		for (BI_IOSequenceGroup gr : groups.values()) {
  			Integer mpNextAvailableSequence = gr.Sequence;
  			Integer countSuccessful = 0;
  			
  			for (CampaignIOResult cr : gr.CampaignResults) {
  				
  				String ioCodeWithoutSegment = GenerateIOCodeOrError(cr);
  				
  				if (!String.isBlank(ioCodeWithoutSegment)) {
  					cr.Campaign.IOCode__c = ioCodeWithoutSegment + padSequenceNumber(mpNextAvailableSequence);
  					cr.Campaign.RequestStatus__c = 'IO Pending';
  					updateCampaigns.add(cr.Campaign);
  					mpNextAvailableSequence++;
  					countSuccessful++;
  				}   				
  				results.add(cr);		
  			}
  			
  			if (countSuccessful > 0) {
  				MarketingPlan__c planToUpdate = new MarketingPlan__c();
  				planToUpdate.Id = gr.MarketingPlanId;
  				planToUpdate.Next_IO_Sequence__c = gr.Sequence + countSuccessful;
  				updatePlans.add(planToUpdate);		
  			}	
  		}
  		
  		// Create a savepoint
		Savepoint sp = Database.setSavepoint();
  		
  		try {  			
			
			//TODO: maybe handle partial transactions?
  			//Try to update all the Campaigns with their new IO Codes and IO Pending status.
  			update updateCampaigns; 			
  			
  			//TODO: maybe handle partial transactions?
  			//Try to update all the Marketing Plans with Next Available Sequence number.
  			update updatePlans;
  			
  		} catch (Exception e) {
  			System.debug(LoggingLevel.INFO,'Exception caught trying to update Campaigns and Marketing Plans: ' + e.getMessage());
  			
  			//Rollback to the savepoint.
  			Database.rollback(sp); 				
  			
  			//Simply add errors on all the Results
  			//TODO: maybe handle partial transactions?
  			for (CampaignIOResult cior : results) {
  				cior.IsSuccess = false;  				
  				cior.Message = getFriendlyError(e.getMessage());  
  			}		
  		}
  		
  		return results;		 		
	}
	
	private static String getFriendlyError(String msg) {
		String defaultMsg = 'A problem occurred while attempting to update Campaign\'s IO Code or update master Marketing Plan\'s Next Available Sequence. All transactions have been reverted.';	
		if (msg == null) { return defaultMsg; }
		
		//Inspect the Exception to determine if a Duplicate IO Code was created.
		if (msg.contains('DUPLICATE_VALUE') == true) { return BI_Constants.IO_DUPLICATE; }
		
		return defaultMsg + '<br/><br/> Exception: ' + msg;
	}
	
	private static String GenerateIOCodeOrError(CampaignIOResult cr) {
		
		if (!IsCampaignValidForIOGeneration(cr)) {
			return null;	
		}		
		
		String ioCode = String.format('{0}{1}{2}', new List<String>{
			cr.Campaign.Brand_Quality__r.IOCodeSegment__c,
			cr.Campaign.Year__c.right(2),			
			cr.Campaign.ParentMarketingPlan__r.Territory__r.IOCodeSegment__c });	
					
		return ioCode;
	}
	
	private static Boolean IsCampaignValidForIOGeneration(CampaignIOResult cr) {
		
		//Validate CR not null
		if (cr == null) { return false; }
		
		
		//validate campaign not null
		if (cr.Campaign == null) {
			cr.IsSuccess = false;
			cr.Message = 'Trouble retrieving Campaign information. Please try again.';
			return false;
		}
		
		//Validate IO code doesn't already exist.
		if (!String.isBlank(cr.Campaign.IOCode__c)) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_ALREADYHASIO; 
			return false;
		}
		
		//Validate Year is populated.
		if (cr.Campaign.Year__c == null) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_YEAR_MISSING; 
			return false;
		}
		
		//Validate SAP Controlling Area is populated.
		if (String.isBlank(cr.Campaign.SAP_Controlling_Area__c)) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_SAP_CONTROLLINGAREA; 
			return false;
		}
		
		//Validate SAP Company Code is populated.
		if (String.isBlank(cr.Campaign.SAP_Company_Code__c)) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_SAP_COMPANYCODE;
			return false;
		}
		
		//Validate SAP Cost Center is populated.
		if (String.isBlank(cr.Campaign.SAP_Cost_Center__c)) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_SAP_COSTCENTER; 
			return false;
		}
		
		//Validate Brand Quality is populated.
		if (cr.Campaign.Brand_Quality__r == null || 
			String.isBlank(cr.Campaign.Brand_Quality__r.IOCodeSegment__c) ||
			cr.Campaign.Brand_Quality__r.IOCodeSegment__c.length() != 5) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_BRANDQUALITY; 
			return false;
		}
		
		//Validate Territory is populated on parent marketing plan.
		if (cr.Campaign.ParentMarketingPlan__r == null ||
			cr.Campaign.ParentMarketingPlan__r.Territory__r == null || 
			String.isBlank(cr.Campaign.ParentMarketingPlan__r.Territory__r.IOCodeSegment__c) ||
			cr.Campaign.ParentMarketingPlan__r.Territory__r.IOCodeSegment__c.length() != 2) {
			cr.IsSuccess = false;
			cr.Message = BI_Constants.IO_TERRITORY; 
			return false;	
		}
		
		//TODO: validate we have all fields.
		cr.IsSuccess = true;
		return true;
	}	
	
	private static Map<Id, BI_IOSequenceGroup> GetIOGroupings(set<Id> campaignIds) {
		
		List<Campaign__c> camps  = [SELECT Id, Name, Year__c, IOCode__c, RequestStatus__c,
			Brand_Quality__r.IOCodeSegment__c,
			SAP_Controlling_Area__c,
			SAP_Company_Code__c,
			SAP_Cost_Center__c,
			ParentMarketingPlan__c,			 
			ParentMarketingPlan__r.Territory__r.IOCodeSegment__c,  
			ParentMarketingPlan__r.Next_IO_Sequence__c 
			FROM Campaign__c
			WHERE Id IN :campaignIds];
			
		//Temp storage for unique MPs.		
		Map<Id, BI_IOSequenceGroup> groupings = new Map<Id, BI_IOSequenceGroup>();
		
		for (Campaign__c c : camps) {
			
			BI_IOSequenceGroup temp = groupings.get(c.ParentMarketingPlan__c);
								
			if (temp == null) {	
				
				//If we dont already have a MarketingPlanSequence for the parent Plan, create one.				
				temp = new BI_IOSequenceGroup();
				temp.MarketingPlanId = c.ParentMarketingPlan__c;
				temp.Sequence = getSequenceSafely(c.ParentMarketingPlan__r.Next_IO_Sequence__c);
				temp.CampaignResults.add(new CampaignIOResult(c));
				groupings.put(c.ParentMarketingPlan__c, temp);
				
			} else {
				
				//We already have one, simply add the Campaign to the list.
				temp.CampaignResults.add(new CampaignIOResult(c));
			}			 
		} 					
		
		return groupings;
	}
	
	private static Integer getSequenceSafely(Decimal sequence) {
		if (sequence == null || sequence <= 0) { 
			return 1; 
		} else {
			return sequence.intValue(); 
		}			
	}	
	
	private static String padSequenceNumber(Integer sequence) {		
		if (sequence == null) {
			 return '001';	
		} else {
			return String.valueOf(sequence).leftPad(3).replaceAll(' ','0');			
		}	
	}
}