src/objects/Campaign__c.object
<CustomObject>
    <description>Campaign records for all Marketing Plans.</description>
    <fields>
        <fullName>ActualCampaignSpend__c</fullName>
        <description>Sum of Actual spend sent from SAP.</description>
        <inlineHelpText>Sum of Actual Spend sent from SAP.</inlineHelpText>
        <label>Actual Campaign Spend</label>
        <summarizedField>Campaign_Spend__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Campaign_Spend__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Actual</value>
        </summaryFilterItems>
        <summaryForeignKey>Campaign_Spend__c.ParentCampaign__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Brand_Quality__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand Quality</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Tags__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Brand Quality</value>
            </filterItems>
            <filterItems>
                <field>Tags__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tags__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand inherited from parent Marketing Plan.</description>
        <formula>ParentMarketingPlan__r.Brand__r.Name</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignBalance__c</fullName>
        <description>Campaign Budget - (Actual Campaign Spend + Committed Campaign Spend)</description>
        <formula>PlannedCampaignSpend__c  - ( ActualCampaignSpend__c  +  CommittedCampaignSpend__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Campaign Budget - (Actual Campaign Spend + Committed Campaign Spend).</inlineHelpText>
        <label>Campaign Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CampaignBrand__c</fullName>
        <label>Campaign Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Ardmore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auchentoshan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basil Hayden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bowmore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calico Jack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cien Anos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cien Anos RTD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Courvoisier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruzan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeKuyper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>El Tesoro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glen Garioch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hacienda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hornitos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Whiskeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Apple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Devils Cut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Flavors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Ghost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Red Stag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kamora</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kessler Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knob Creek</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laphroaig</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Larios</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Makers Mark</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Used to capture Budget comments anytime Budget is modified.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CommittedCampaignSpend__c</fullName>
        <description>Sum of Committed Spend sent from SAP.</description>
        <inlineHelpText>Sum of Committed Spend sent from SAP.</inlineHelpText>
        <label>Committed Campaign Spend</label>
        <summarizedField>Campaign_Spend__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Campaign_Spend__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Committed</value>
        </summaryFilterItems>
        <summaryForeignKey>Campaign_Spend__c.ParentCampaign__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>IOCode__c</fullName>
        <label>IO Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InitialEndDate__c</fullName>
        <description>Initial end date of the Campaign.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InitialStartDate__c</fullName>
        <description>Initial start date of the Campaign.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentMarketingPlan__c</fullName>
        <label>Master Marketing Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - FIELD</value>
            </filterItems>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - NATL MKTG</value>
            </filterItems>
            <filterItems>
                <field>MarketingPlan__c.MP_Type__c</field>
                <operation>equals</operation>
                <value>TERRITORY - NATL ACCTS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MarketingPlan__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PlannedCampaignSpend__c</fullName>
        <label>Campaign Budget</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MarketingPlan__c.object
<CustomObject>
    <description>Marketing Plan Budget records for all levels of the hierarchy.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Tags__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Brand</value>
            </filterItems>
            <filterItems>
                <field>Tags__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tags__c</referenceTo>
        <relationshipLabel>Marketing Plans (Brand)</relationshipLabel>
        <relationshipName>Marketing_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CampaignBalance__c</fullName>
        <description>(MP Budget - Campaign Budget) if Record Type equals &quot;Campaigns Allowed - Editable&quot; or &quot;Campaigns Allowed - Not Editable&quot;.</description>
        <formula>IF((   RecordType.Name   =&quot;Campaigns Allowed - Editable&quot;),( Budget__c  -  CampaignBudget__c),  IF((RecordType.Name=&quot;Campaigns Allowed - Not Editable&quot;), ( Budget__c  -  CampaignBudget__c), null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MP Budget - Campaign Budget.</inlineHelpText>
        <label>Campaign Unallocated Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Free form text field to allow for comments on any updates made to the Marketing Plan budgets</description>
        <inlineHelpText>Comment field for any updates made to budget.</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ParentMarketingPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Marketing Plan</label>
        <referenceTo>MarketingPlan__c</referenceTo>
        <relationshipLabel>Related Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tags__c.object
<CustomObject>
    <description>Brand, Brand Quality, and Territory hierarchy data table.</description>
    <fields>
        <fullName>CampaignBrand__c</fullName>
        <label>Campaign Brand</label>
        <picklist>
            <picklistValues>
                <fullName>100 Anos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 Anos RTD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta Rye</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alberta Springs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ardmore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auchentoshan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banff Ice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basil Hayden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bowmore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calico Jack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooleys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Courvoisier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruzan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeKuyper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>El Tesoro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glengarioch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glen Garioch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hacienda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hibiki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hornitos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Whiskeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Apple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Devils Cut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Fire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Beam Flavors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tag</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Brand Record Type.</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignMultiRecordEditor.cls
public with sharing class CampaignMultiRecordEditor extends PageControllerBase {
    public Boolean MyAllowCreateIO {get; set;}
    public Boolean MyAllowAdd {get; set;}
    public Boolean MyAllowEdit {get; set;}
    public Boolean MyAllowDelete {get; set;}  
      
    public String MysObj {get; set;}
    public String MyRecId {get; set;}
    public String MyRelationField {get; set;}    
    public list<String> MyFieldList {get; set;}
    public list<String> MySearchFieldList {get; set;}
    public list<String> MyLabelOverrideFieldList {get; set;}
    public list<String> MyLabelOverrideTextList {get; set;}
    public list<String> MyDefaultValueFieldList {get; set;}
    public list<String> MyDefaultValueTextList {get; set;}
    
    public String MyBlockTitle {get; set;}
    public ApexPages.StandardController standardController {get; set; }
 
    public CampaignMultiRecordEditor(ApexPages.StandardController stdController) {
        this.standardController = stdController;
        Id recordId = this.standardController.getId();
        MyAllowAdd = true;
        MyAllowEdit = true;
        MyAllowDelete = false;
        
        //For Create IO Button
        MyAllowCreateIO = true;
        
        MyBlockTitle = 'Edit Campaigns';
        MysObj = 'Campaign__c';
        MyRecId = '' + recordId; 
        MyRelationField = 'ParentMarketingPlan__c';
        MyFieldList = new list<String> {'IOCode__c',
                                        'Name',
                                        'Brand_Quality__c',
                                        'PlannedCampaignSpend__c',
                                        'ActualCampaignSpend__c',
                                        'CommittedCampaignSpend__c',
                                        'CampaignBalance__c',                                                                                
                                        'Comments__c',
                                        'InitialStartDate__c',
                                        'InitialEndDate__c',
                                        //'CampaignBrand__c',
                                        'CampaignType__c',
                                        'GLAccountType__c',
                                        'GLDescription__c',
                                        'GLCode__c',
                                        'Description__c'
                                         };        
                                      
         
        MySearchFieldList = new list<String> {  'Name',
                                                'IOCode__c',                                                                
                                                'CampaignType__c',
                                                'GLAccountType__c',
                                                'GLDescription__c'};
        MyLabelOverrideFieldList = new list<String> {   'CampaignBrand__c',
                                                        'PlannedCampaignSpend__c',
                                                        'CampaignBalance__c',
                                                        'ActualCampaignSpend__c',
                                                        'CommittedCampaignSpend__c' };
        MyLabelOverrideTextList = new list<String> {    'Brand',
                                                        'Budget',
                                                        'Balance',
                                                        'Actual',
                                                        'Committed',
                                                        'Description' };
        
         String defaultCampaignBrand = [SELECT Brand__r.CampaignBrand__c
            FROM MarketingPlan__c 
            WHERE Id = :recordId].Brand__r.CampaignBrand__c;
        System.debug(LoggingLevel.INFO,'Default CampaignBrand: ' + defaultCampaignBrand);
            
            //'CampaignBrand__c', 'Strategy__c', 'Objective__c', 'CampaignType__c', 'GLAccountType__c', 'GLCode__c'
        MyDefaultValueFieldList = new list<String> { 'CampaignBrand__c' };
        MyDefaultValueTextList = new list<String> { defaultCampaignBrand };
    }
        
    public override void RefreshPage() {
        //Without Test.isRunningTest(), this lines errors because of the following sObject error:
        //System.SObjectException: You cannot call reset when the data is being passed into the controller by the caller.
        if (!Test.isRunningTest()) {
            this.standardController.reset();    
        } 
    }
}